name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    environment:
      name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout
    - name: set env
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        YOUR_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/csdp-report-image-github-action:demo2
        YOUR_IMAGE_NAME: csdp-report-image-github-action
        ENRICHERS: "jira"
        CF_HOST: "https://g.codefresh.io"
        VERBOSE: "1"
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        ABC: DEF
      run: |
        echo "DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME" >> $GITHUB_ENV
        echo "YOUR_IMAGE_NAME=$YOUR_IMAGE_NAME" >> $GITHUB_ENV
        echo "YOUR_IMAGE=$YOUR_IMAGE" >> $GITHUB_ENV
        echo "ABC=$ABC" >> $GITHUB_ENV
        echo "VERBOSE=$VERBOSE" >> cf_env
        echo "CF_API_KEY=$CF_API_KEY" >> cf_env
        echo "CF_HOST=$CF_HOST" >> cf_env
        echo "CF_IMAGE=$YOUR_IMAGE" >> cf_env
        echo "ENRICHERS=$ENRICHERS" >> cf_env
        cat cf_env >> $GITHUB_ENV
    - name: print env
      run: |
        echo "Env has YOUR_IMAGE=> $YOUR_IMAGE"
        echo "Env has DOCKERHUB_USERNAME=> $DOCKERHUB_USERNAME"
        echo "Env has CF_IMAGE=> $CF_IMAGE"
        cat cf_env
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build & push the Docker image
      run: |
        cat cf_env
        docker build . --file Dockerfile --tag $CF_IMAGE && docker push $CF_IMAGE
    - name: Report image
      run: |
        docker run --env-file=$GITHUB_ENV safficodefresh/csdp-report-image:latest
