name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    environment:
      name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout
    - name: set env
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        YOUR_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/csdp-report-image-github-action:demo2
        YOUR_IMAGE_NAME: csdp-report-image-github-action
        ENRICHERS: "jira"
        CF_HOST: "https://g.codefresh.io"
        VERBOSE: "1"
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        ABC: DEF
      run: |
        echo "DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME" >> $GITHUB_ENV
        echo "YOUR_IMAGE_NAME=$YOUR_IMAGE_NAME" >> $GITHUB_ENV
        echo "VERBOSE=$VERBOSE" >> $GITHUB_ENV
        echo "CF_API_KEY=$CF_API_KEY" >> $GITHUB_ENV
        echo "CF_HOST=$CF_HOST" >> $GITHUB_ENV
        echo "CF_IMAGE=$YOUR_IMAGE" >> $GITHUB_ENV
        echo "ENRICHERS=$ENRICHERS" >> $GITHUB_ENV
        echo "YOUR_IMAGE=$YOUR_IMAGE" >> $GITHUB_ENV
        echo "ABC=$ABC" >> $GITHUB_ENV
    - name: print env
      run: |
        echo "Env has YOUR_IMAGE=> $YOUR_IMAGE"
        echo "Env has DOCKERHUB_USERNAME=> $DOCKERHUB_USERNAME"
        echo "Env has CF_IMAGE=> $CF_IMAGE"
        echo "Env has ABC=> $ABC"
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build & push the Docker image
      run: |
        docker build --file Dockerfile --tag $CF_IMAGE
        echo docker push $CF_IMAGE
    - name: Report image
      run: |
#        echo $GITHUB_ENV
##        base64 -i $GITHUB_ENV > output
##        cat output
#        echo "ABC=DEF" > cf_env
#        cat $GITHUB_ENV
#        cp $GITHUB_ENV cf_env
#        cat cf_env
#        docker run  --env-file cf_env safficodefresh/csdp-report-image:latest sh -c 'env && ls -ltr && echo "sample abc: $ABC" '
        docker run -e CF_API_KEY=$CF_API_KEY -e CF_IMAGE=$CF_IMAGE safficodefresh/csdp-report-image:latest
#    - name: Build and push
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        file: ./Dockerfile
#        push: true
#        tags: $CF_IMAGE
