name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set env
      env:
        YOUR_IMAGE_NAME: "csdp-report-image-github-action"
      run: |
        export YOUR_IMAGE="safficodefresh/$YOUR_IMAGE_NAME:demo"
        echo "YOUR_IMAGE=$YOUR_IMAGE" >> $GITHUB_ENV
    - name: print env
      run: |
        echo "Env has YOUR_IMAGE=> $YOUR_IMAGE"
        echo "Env has CF_IMAGE=> $CF_IMAGE"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $YOUR_IMAGE
    - name: push image to repo - echo the command instead of performing it
      run: |
        echo "docker login"  
        echo "docker push $YOUR_IMAGE"
    - name: Report image
      env:
        VERBOSE: "1"
        CF_API_KEY: "62245e6757660232167442d5.7ef491f9feac5d36a937836a53436303"
        CF_IMAGE: "$YOUR_IMAGE"
        ENRICHERS: "jira"
      run: docker run safficodefresh/csdp-report-image:latest -e VERBOSE:$VERBOSE

